# Используем официальный образ Node.js
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект в контейнер
COPY . .

# Указываем порт, на котором работает бэкенд
EXPOSE 8080

# Команда для запуска приложения
CMD ["node", "app.js"]